version: '3.8'

services:
  # 1. The Backend (Node.js)
  kebundata-api:
    build: ./kebundata-backend
    restart: always
    ports:
      - "3000:3000"
    # environment: ... (We will fix this in a moment)

  # 2. The Frontend (Nginx)
  kebundata-dashboard:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./kebundata-dashboard:/usr/share/nginx/html
