version: '3.3'

services:
  kebundata-dashboard:
    image: nginx:alpine
    container_name: kebundata_dashboard
    restart: unless-stopped
    volumes:
      - ./kebundata-dashboard:/usr/share/nginx/html
    ports:
      - "8081:80"
