version: '3.3'

services:
  # 1. The Backend
  kebundata-api:
    build: ./kebundata-backend
    restart: always
    ports:
      - "3000:3000"
    # environment: ... 

  # 2. The Frontend (Nginx)
  kebundata-frontend:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./kebundata-frontend:/usr/share/nginx/html
